title: To Linh's house
author: To Linh
email: tolinh.tran91@gmail.com
copyright: © 2019 GitHub User
description: > # this means to ignore newlines until "show_excerpts:"
  As a data analyst and data scientist with theorical Mathematics foundation, I visualize data into valuable, comprehensible and logical insights. My goal is to bright up results, consult customers save costs. I am experienced in Pure Mathamtics (PhD Candidate), data analysist, data scientist, supervised and unsupervised algorithms and use data visualization techniques to present the results. I use SQL, R, Python, Azure, Excel and Tableau for my data projects.

show_excerpts: false # set to true to show excerpts on the homepage

lin:
  date_format: "%b %-d, %Y"

  # path to the author avatar image
  avatar_path: assets/images/avatar.jpg

  # generate social links
  social_links:
    github:  tolinh
    facebook: /tolinh91/
    linkedin: tolinhtran

theme: lin

plugins:
 - jekyll-feed
 - jekyll-seo-tag

markdown: kramdown
